version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: cmake .
      - run: make
  build_gcc_7:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run: cmake .
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_7
