version: 2.0
jobs:
  build_gcc_7:
    docker:
      - image: rikorose/gcc-cmake:7
    steps:
      - checkout
      - run: cmake .
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_7
