version: 2.0
jobs:
  build_gcc_7:
    docker:
      - image: rikorose/gcc-cmake:gcc-7
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install libpcsclite-dev -y
      - run: cmake .
      - run: make
  build_gcc_6:
    docker:
      - image: rikorose/gcc-cmake:gcc-6
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install libpcsclite-dev -y
      - run: cmake .
      - run: make
  doxygen:
    docker:
      - image: nnadeau/docker-doxygen
    steps:
      - checkout
      - run: apk update && apk add git ssh
      - run: .circleci/doxygen.sh
      - run: .circleci/push_gh_pages.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      #- build_gcc_7
      #- build_gcc_6
      - doxygen
